insert into authors (id, first_name, last_name) values (1, 'Aldwin', 'Maddison');
insert into authors (id, first_name, last_name) values (2, 'Marlene', 'Claydon');
insert into authors (id, first_name, last_name) values (3, 'Maurits', 'Brende');
insert into authors (id, first_name, last_name) values (4, 'Constantine', 'Garton');
insert into authors (id, first_name, last_name) values (5, 'Kali', 'Barends');
insert into authors (id, first_name, last_name) values (6, 'Courtnay', 'Farleigh');
insert into authors (id, first_name, last_name) values (7, 'Yorke', 'MacDwyer');
insert into authors (id, first_name, last_name) values (8, 'Cristiano', 'Peasey');
insert into authors (id, first_name, last_name) values (9, 'Tod', 'Woolaston');
insert into authors (id, first_name, last_name) values (10, 'Jen', 'Cunney');
insert into authors (id, first_name, last_name) values (11, 'Shalom', 'Rodbourne');
insert into authors (id, first_name, last_name) values (12, 'Collin', 'Spaughton');
insert into authors (id, first_name, last_name) values (13, 'Honoria', 'Matthesius');
insert into authors (id, first_name, last_name) values (14, 'Daron', 'Scarce');
insert into authors (id, first_name, last_name) values (15, 'Khalil', 'Arnull');
insert into authors (id, first_name, last_name) values (16, 'Tisha', 'Dauber');
insert into authors (id, first_name, last_name) values (17, 'Tedd', 'Burles');
insert into authors (id, first_name, last_name) values (18, 'Randie', 'Andreas');
insert into authors (id, first_name, last_name) values (19, 'Karlene', 'Granger');
insert into authors (id, first_name, last_name) values (20, 'Major', 'Mattersley');
insert into authors (id, first_name, last_name) values (21, 'Hatti', 'Skelbeck');

insert into books (id, price, price_old, title, author_id) values (1, 1642, 1843, 'Bitwolf', 1);
insert into books (id, price, price_old, title, author_id) values (2, 707, 1451, 'Tres-Zap', 1);
insert into books (id, price, price_old, title, author_id) values (3, 1590, 2445, 'Daltfresh', 1);
insert into books (id, price, price_old, title, author_id) values (4, 2951, 2425, 'Namfix', 1);
insert into books (id, price, price_old, title, author_id) values (5, 2267, 2139, 'Sonsing', 1);
insert into books (id, price, price_old, title, author_id) values (6, 2403, 1007, 'Bytecard', 1);
insert into books (id, price, price_old, title, author_id) values (7, 2271, 3149, 'Tempsoft', 1);
insert into books (id, price, price_old, title, author_id) values (8, 2855, 3279, 'Holdlamis', 1);
insert into books (id, price, price_old, title, author_id) values (9, 1857, 1329, 'Fix San', 1);
insert into books (id, price, price_old, title, author_id) values (10, 2569, 1961, 'Ventosanzap', 1);
insert into books (id, price, price_old, title, author_id) values (11, 1429, 3820, 'Toughjoyfax', 1);
insert into books (id, price, price_old, title, author_id) values (12, 1204, 1226, 'Sub-Ex', 1);
insert into books (id, price, price_old, title, author_id) values (13, 1838, 2604, 'Bigtax', 1);
insert into books (id, price, price_old, title, author_id) values (14, 661, 2748, 'Rank', 1);
insert into books (id, price, price_old, title, author_id) values (15, 2202, 2667, 'Matsoft', 1);
insert into books (id, price, price_old, title, author_id) values (16, 1666, 1960, 'Konklux', 1);
insert into books (id, price, price_old, title, author_id) values (17, 2855, 1371, 'Konklab', 1);
insert into books (id, price, price_old, title, author_id) values (18, 1409, 2659, 'Fintone', 2);
insert into books (id, price, price_old, title, author_id) values (19, 862, 2119, 'Prodder', 2);
insert into books (id, price, price_old, title, author_id) values (20, 2954, 1399, 'Zontrax', 2);
insert into books (id, price, price_old, title, author_id) values (21, 2307, 3157, 'Lotstring', 4);
insert into books (id, price, price_old, title, author_id) values (22, 1457, 1790, 'Duobam', 3);
insert into books (id, price, price_old, title, author_id) values (23, 744, 3184, 'Subin', 3);
insert into books (id, price, price_old, title, author_id) values (24, 2923, 1681, 'Opela', 3);
insert into books (id, price, price_old, title, author_id) values (25, 1304, 3447, 'Andalax', 3);
insert into books (id, price, price_old, title, author_id) values (26, 2099, 3218, 'Otcom', 4);
insert into books (id, price, price_old, title, author_id) values (27, 2623, 2155, 'Stronghold', 4);
insert into books (id, price, price_old, title, author_id) values (28, 2667, 2987, 'Konklux', 4);
insert into books (id, price, price_old, title, author_id) values (29, 1499, 2124, 'Temp', 5);
insert into books (id, price, price_old, title, author_id) values (30, 942, 1684, 'Quo Lux', 6);
insert into books (id, price, price_old, title, author_id) values (31, 2535, 3723, 'Treeflex', 3);
insert into books (id, price, price_old, title, author_id) values (32, 1157, 2477, 'Toughjoyfax', 5);
insert into books (id, price, price_old, title, author_id) values (33, 2074, 2228, 'Flexidy', 5);
insert into books (id, price, price_old, title, author_id) values (34, 2979, 2258, 'Home Ing', 5);
insert into books (id, price, price_old, title, author_id) values (35, 959, 1785, 'Redhold', 5);
insert into books (id, price, price_old, title, author_id) values (36, 1082, 1052, 'Tampflex', 6);
insert into books (id, price, price_old, title, author_id) values (37, 2799, 1801, 'Vagram', 6);
insert into books (id, price, price_old, title, author_id) values (38, 1142, 2837, 'Fix San', 7);
insert into books (id, price, price_old, title, author_id) values (39, 2280, 2482, 'Voltsillam', 8);
insert into books (id, price, price_old, title, author_id) values (40, 900, 1383, 'Tresom', 9);
insert into books (id, price, price_old, title, author_id) values (41, 1913, 2287, 'Ronstring', 9);
insert into books (id, price, price_old, title, author_id) values (42, 920, 2045, 'Otcom', 9);
insert into books (id, price, price_old, title, author_id) values (43, 2574, 3635, 'Fix San', 9);
insert into books (id, price, price_old, title, author_id) values (44, 1820, 2662, 'Zaam-Dox', 9);
insert into books (id, price, price_old, title, author_id) values (45, 1416, 1165, 'Zoolab', 19);
insert into books (id, price, price_old, title, author_id) values (46, 2370, 3331, 'Vagram', 2);
insert into books (id, price, price_old, title, author_id) values (47, 2914, 1815, 'Asoka', 6);
insert into books (id, price, price_old, title, author_id) values (49, 2500, 2518, 'Tampflex', 16);
insert into books (id, price, price_old, title, author_id) values (50, 545, 2576, 'Rank', 16);
insert into books (id, price, price_old, title, author_id) values (51, 2873, 1011, 'Daltfresh', 16);
insert into books (id, price, price_old, title, author_id) values (52, 2127, 2419, 'Sub-Ex', 2);
insert into books (id, price, price_old, title, author_id) values (53, 1458, 3717, 'Greenlam', 15);
insert into books (id, price, price_old, title, author_id) values (54, 695, 2852, 'Namfix', 15);
insert into books (id, price, price_old, title, author_id) values (56, 2698, 1297, 'Tresom', 17);
insert into books (id, price, price_old, title, author_id) values (57, 1994, 3990, 'Zamit', 6);
insert into books (id, price, price_old, title, author_id) values (58, 1404, 3637, 'Regrant', 20);
insert into books (id, price, price_old, title, author_id) values (59, 1140, 2623, 'Biodex', 15);
