insert into authors (id, first_name, last_name) values (1, 'Carlos', 'Dodshon');
insert into authors (id, first_name, last_name) values (2, 'Jelene', 'Hopfner');
insert into authors (id, first_name, last_name) values (3, 'Dannye', 'Wickendon');
insert into authors (id, first_name, last_name) values (4, 'Alec', 'Shurrock');
insert into authors (id, first_name, last_name) values (5, 'Nadia', 'Brabham');
insert into authors (id, first_name, last_name) values (6, 'Silvie', 'Gateland');
insert into authors (id, first_name, last_name) values (7, 'Sharai', 'Feighney');
insert into authors (id, first_name, last_name) values (8, 'Andres', 'Djorevic');
insert into authors (id, first_name, last_name) values (9, 'Deeanne', 'Rivitt');
insert into authors (id, first_name, last_name) values (10, 'Javier', 'MacCallister');
insert into authors (id, first_name, last_name) values (11, 'Ami', 'Ramsbotham');
insert into authors (id, first_name, last_name) values (12, 'Georges', 'Smiley');
insert into authors (id, first_name, last_name) values (13, 'Nichol', 'Brick');
insert into authors (id, first_name, last_name) values (14, 'Dorris', 'Eastup');
insert into authors (id, first_name, last_name) values (15, 'Ewen', 'Chrestien');
insert into authors (id, first_name, last_name) values (16, 'Allin', 'Gilluley');
insert into authors (id, first_name, last_name) values (17, 'Verney', 'Lambdon');
insert into authors (id, first_name, last_name) values (18, 'Margalit', 'Mitten');
insert into authors (id, first_name, last_name) values (19, 'Rhonda', 'Peterson');
insert into authors (id, first_name, last_name) values (20, 'Melinde', 'Badsey');
insert into authors (id, first_name, last_name) values (21, 'Alexander', 'Cherrington');

insert into books (id, price, price_old, title, author_id) values (1, 2610, 2805, 'Trippledex', 21);
insert into books (id, price, price_old, title, author_id) values (2, 1138, 2661, 'Alpha', 15);
insert into books (id, price, price_old, title, author_id) values (3, 695, 2490, 'Viva', 12);
insert into books (id, price, price_old, title, author_id) values (4, 2115, 2457, 'Voltsillam', 3);
insert into books (id, price, price_old, title, author_id) values (5, 2833, 2303, 'Treeflex', 2);
insert into books (id, price, price_old, title, author_id) values (6, 2151, 2533, 'Treeflex', 2);
insert into books (id, price, price_old, title, author_id) values (7, 1288, 3215, 'Stringtough', 2);
insert into books (id, price, price_old, title, author_id) values (8, 1580, 2810, 'Daltfresh', 6);
insert into books (id, price, price_old, title, author_id) values (9, 2360, 1807, 'Y-Solowarm', 20);
insert into books (id, price, price_old, title, author_id) values (10, 2283, 2398, 'Duobam', 2);
insert into books (id, price, price_old, title, author_id) values (11, 1423, 3346, 'Home Ing', 7);
insert into books (id, price, price_old, title, author_id) values (12, 1660, 1211, 'Gembucket', 6);
insert into books (id, price, price_old, title, author_id) values (13, 637, 2324, 'Voltsillam', 3);
insert into books (id, price, price_old, title, author_id) values (14, 1877, 1277, 'Y-find', 5);
insert into books (id, price, price_old, title, author_id) values (15, 1549, 1670, 'Home Ing', 9);
insert into books (id, price, price_old, title, author_id) values (16, 1489, 1157, 'Rank', 16);
insert into books (id, price, price_old, title, author_id) values (17, 1988, 3949, 'Home Ing', 9);
insert into books (id, price, price_old, title, author_id) values (18, 1185, 3979, 'Opela', 13);
insert into books (id, price, price_old, title, author_id) values (19, 2376, 2833, 'Home Ing', 18);
insert into books (id, price, price_old, title, author_id) values (20, 2303, 3676, 'Duobam', 12);
insert into books (id, price, price_old, title, author_id) values (21, 1766, 3174, 'Otcom', 13);