package com.example.MyBookShopApp.data.entity.book;

import com.example.MyBookShopApp.data.Author;
import com.example.MyBookShopApp.data.Book;
import com.example.MyBookShopApp.data.entity.book.file.BookFileEntity;
import com.example.MyBookShopApp.data.entity.book.review.BookReviewEntity;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "book_sorted")
@ApiModel(description = "entity representing a book")
public class BookSorted {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @ApiModelProperty("id generated by db automatically")
    private Integer id;

    private Double rating;

    @OneToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "bookSorted_id", referencedColumnName = "id")
    @JsonIgnore
    private Book book;

    public void setId(Integer id) {
        this.id = id;
    }

    public void setRating(Double rating) {
        this.rating = rating;
    }


    public Integer getId() {
        return id;
    }

    public Double getRating() {
        return rating;
    }

    public Book getBook() {
        return book;
    }

    public void setBook(Book book) {
        this.book = book;
    }

    @Override
    public String toString() {
        return "BookSorted{" +
                "id=" + id +
                ", rating=" + rating +
                ", book=" + book +
                '}';
    }
}
